# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVT8upCk-LDDJpd2OokxwQxtN8kP3mO5
"""

import streamlit as st
import pickle
import numpy as np
import requests
from geopy.geocoders import Nominatim
import folium
from streamlit_folium import folium_static
from folium.plugins import HeatMap
import pandas as pd
from folium.plugins import HeatMap
# ===== CONFIG =====
st.set_page_config(page_title="Dự đoán giá phòng", layout="centered")

# ===== STYLE =====
st.markdown("""
<style>

/* Nền toàn app */
.stApp {
    background: linear-gradient(135deg, #ff9a9e, #fecfef);
}

/* Xoá nền trắng mặc định */
.block-container {
    background: transparent !important;
}

/* Input sáng nhẹ */
.stTextInput, .stNumberInput, .stSelectbox {
    background-color: rgba(255,255,255,0.25);
    border-radius: 12px;
    padding: 10px;
}

/* Label */
label {
    color: #333 !important;
    font-weight: 600;
}

/* Nút nổi */
.stButton button {
    background: linear-gradient(90deg, #ff4b2b, #ff416c);
    color: white;
    border-radius: 12px;
    height: 50px;
    font-size: 18px;
    width: 100%;
    border: none;
    box-shadow: 0 4px 15px rgba(0,0,0,0.2);
}

/* Card kết quả trắng */
.result-box {
    background: white;
    padding: 25px;
    border-radius: 16px;
    text-align: center;
    box-shadow: 0 6px 20px rgba(0,0,0,0.2);
}

</style>
""", unsafe_allow_html=True)

# ===== HEADER =====
st.markdown("""
<h1 style='text-align: center;'>🏠 Dự đoán giá phòng trọ</h1>
<p style='text-align: center; color: gray;'>Nhập thông tin → nhận giá dự đoán ngay</p>
""", unsafe_allow_html=True)

# ===== LOAD MODEL =====
model = pickle.load(open("model.pkl", "rb"))
df_heat = pd.read_excel("/content/heatmap_data.xlsx")

# ===== API KEY =====
API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjM3NDA2ODBlMDljNDQ0NTliMjNhM2ZlMTQzZGQwZmY4IiwiaCI6Im11cm11cjY0In0="

# ===== CƠ SỞ =====
campuses = {
    "UEH - Cơ sở A ": (106.694641461485,10.783316576715869),
    "UEH - Cơ sở B ": (106.66833758534004,10.761275283435763),
    "UEH - Cơ sở N ": (106.64013851737563,10.706324249079467)
}

# ===== LAYOUT 2 CỘT =====
col1, col2 = st.columns(2)

with col1:
    address = st.text_input("📍 Địa chỉ")
    area = st.number_input("📐 Diện tích (m²)", min_value=0.0)

with col2:
    so_nguoi = st.number_input("👥 Số người", min_value=1)
    campus_name = st.selectbox("🏫 Cơ sở", list(campuses.keys()))

# ===== OPTION =====
tien_nghi = st.selectbox("❄️ Tiện nghi", ["Có", "Không"])
gio_giac = st.selectbox("⏰ Giờ giấc tự do", ["Có", "Không"])
tien_ich = st.selectbox("🏪 Tiện ích xung quanh", ["Có", "Không"])

# ===== CONVERT =====
tien_nghi = 1 if tien_nghi == "Có" else 0
gio_giac = 1 if gio_giac == "Có" else 0
tien_ich = 1 if tien_ich == "Có" else 0

# ===== GEOCODE =====
def geocode(address):

    try:
        geolocator = Nominatim(user_agent="rent_app")

        location = geolocator.geocode(
            address,
            timeout=10
        )

        if location:
            return (
                location.longitude,
                location.latitude
            )

        return None

    except:
        return None

# ===== DISTANCE =====
def get_distance(coord1, coord2):
    url = "https://api.openrouteservice.org/v2/directions/driving-car"

    headers = {
        "Authorization": API_KEY,
        "Content-Type": "application/json"
    }

    body = {
        "coordinates": [
            [coord1[0], coord1[1]],
            [coord2[0], coord2[1]]
        ]
    }

    response = requests.post(
        url,
        json=body,
        headers=headers
    )

    data = response.json()

    if "routes" not in data:
        return None

    return data["routes"][0]["summary"]["distance"] / 1000
# ===== BUTTON =====
if st.button("🔮 Dự đoán ngay"):
    geo = geocode(address)

    if geo is None:
        st.error("❌ Không tìm được địa chỉ")
    else:
        campus_coord = campuses[campus_name]

        try:
            distance = get_distance(geo, campus_coord)
            if distance is None:
              st.error("❌ Không lấy được khoảng cách")
              st.stop()

            features = np.array([[distance, area, tien_nghi, gio_giac, so_nguoi, tien_ich]])
            price = model.predict(features)[0]

            # ===== RESULT CARD =====
            st.markdown(f"""
            <div style='background-color:#1e1e2f;padding:20px;border-radius:15px;text-align:center;'>
                <h3 style='color:#00ffcc;'>📏 {distance:.2f} km</h3>
                <h2 style='color:#ff4b4b;'>💰 {int(price):,} VND</h2>
                <p style='color:gray;'>Giá dự đoán</p>
            </div>
            """, unsafe_allow_html=True)

            # ===== TOẠ ĐỘ =====
            room_lat = geo[1]
            room_lon = geo[0]

            campus_lat = campus_coord[1]
            campus_lon = campus_coord[0]

            # ===== MAP =====
            m = folium.Map(
            location=[room_lat, room_lon],
            zoom_start=14)

            # ===== HEAT DATA =====
            heat_data = []

            for _, row in df_heat.iterrows():

              if pd.notna(row["lat"]) and pd.notna(row["lon"]):

                heat_data.append([
                  row["lat"],
                  row["lon"],
                  row["price"] / 1000000
                  ])

            # Heatmap
            HeatMap(
            heat_data,
            radius=50,
            blur=30,
            min_opacity=0.4
            ).add_to(m)

            # Marker phòng
            folium.Marker(
            [room_lat, room_lon],
            tooltip="📍 Phòng trọ"
            ).add_to(m)

            # Marker campus
            folium.Marker(
            [campus_lat, campus_lon],
            tooltip="🏫 Campus",
            icon=folium.Icon(color="red")
            ).add_to(m)

            # Đường nối
            folium.PolyLine(
            [
            [room_lat, room_lon],
            [campus_lat, campus_lon]
            ],
            color="blue",
            weight=4
            ).add_to(m)

            # ===== HIỂN THỊ =====
            st.subheader("🗺️ Heatmap giá phòng")

            folium_static(m)

        except Exception as e:
         st.error(f"Lỗi: {e}")